# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

    # Setup Ruby and Bundler
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true 
         
      - name: Setup node
        uses: actions/setup-node@v2.5.0
        
   # Not needed if `bundler-cache: true`   
      #- name: Install project gems
      #  run: bundle install
          
      - name: Install & start Appium Server
        run: |
          npm install -g appium
          appium -v
          appium &>/dev/null &
          
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-23

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 23
          force-avd-creation: false 
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false 
          script: echo "Generated AVD snapshot for caching."
          
      - name: Android Emulator Runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 23
          working-directory: ./tests
          force-avd-creation: false 
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true 
          script: bundle exec rspec *.rb --format html --out rspec_results.html
          
      - name: Archive test coverage results
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage-report
          path: tests/rspec_results.html
